# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force=true
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  # Allows for page view components to be dynamically linked
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
